apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: schemas-topic
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: schema-registry-schemas-topic
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: "compact"
