apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-spark-ivy-cache
  namespace: spark-jobs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-spark-ivy-cache
  namespace: spark-operator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

