apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-spark-ivy-cache
  namespace: spark-jobs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-rwx-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-spark-history-server
  namespace: spark-jobs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-rwx-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
