apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: control-power-avro
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  topicName: control_power-avro
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: robot-avro
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  topicName: robot-avro
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: accelerometer-gyro-avro
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  topicName: accelerometer_gyro-avro
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: control-power-json
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  topicName: control_power-json
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: robot-json
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  topicName: robot-json
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: accelerometer-gyro-json
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  topicName: accelerometer_gyro-json
---

