{
 "title": "Apache Spark - Performance Metrics",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": "label_values(kube_pod_info, pod)"
   },
   {
    "name": "Pod_ip",
    "query": "label_values(kube_pod_info{pod=\"$Pod\"}, node)"
   },
   {
    "name": "phase",
    "query": "query_result(kube_pod_status_phase{pod=\"$Pod\"})"
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": "label_values(kube_pod_info{created_by_name=~\"$Pod\"},pod)"
   },
   { "name": "copy_of_phase" }
  ]
 },
 "panels": [
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Driver IP Address", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 }, "repeat": "Pod" },
  { "title": "Driver Status", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 }, "repeat": "Pod" },
  {
   "title": "Total Cluster Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total Cluster CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Driver Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Driver Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{pod=~\".*-driver\", container!=\"\", container!=\"POD\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}))* 100"
    }
   ]
  },
  {
   "title": "Executor Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum (container_memory_working_set_bytes{pod=~\".*-exec-.*\", container!=\"\", container!=\"POD\"}) /sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\".*-driver\", container!=\"\", container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\".*-exec-.*\", container!=\"\", container!=\"POD\"})"
    }
   ]
  },
  { "title": "Driver CPU / Memory  usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Driver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "repeat": "Pod",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*-driver\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Driver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*-driver\", container!=\"\", container!=\"POD\"} [2m])) by (pod) ",
     "legendFormat": "Used CPU : {{pod}}"
    }
   ]
  },
  {
   "title": "Driver GC : Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{pod=~\".*-driver\", container!=\"\", container!=\"POD\", gc=\"PS Scavenge\"}[2m])",
     "legendFormat": "{{ gc }}"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_count{pod=~\"$Pod\", gc=\"PS MarkSweep\"}[2m])",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  { "title": "Executor CPU /Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Executor :  Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*-exec-.*\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Executor  :  CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*-exec-.*\", container!=\"\", container!=\"POD\"} [4m])) by (pod_name) ",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Executor GC : Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{pod_name=~\"$executor\",gc=\"PS Scavenge\"}[2m])",
     "legendFormat": "{{ kubernetes_pod_name }} {{ gc }}"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_count{pod_name=~\"$executor\",gc=\"PS MarkSweep\"}[2m])",
     "legendFormat": "{{ kubernetes_pod_name }} {{ gc }}"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Driver Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$Pod'}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$Pod'}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'$executor',kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'$executor',pod_name!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\".*-driver|.*-exec-.*\", device=~\"/dev/.*\"}[2m])) by (pod, device)",
     "legendFormat": "{{pod}} {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\".*-driver|.*-exec-.*\", device=~\"/dev/.*\"}[2m])) by (pod, device)",
     "legendFormat": "{{pod }}{{device}} Write"
    }
   ]
  },
  { "title": "Spark External Shuffle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Spark Shuffle Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'.*shuffle.*',kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod,kubernetes_io_hostname)",
     "legendFormat": "{{ pod }} {{kubernetes_io_hostname}} Transmitted"
    }
   ]
  },
  {
   "title": "Spark Shuffle Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'.*shuffle.*',pod!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod,kubernetes_io_hostname)",
     "legendFormat": "{{ pod }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }} {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod,device)",
     "legendFormat": "{{pod}}{{device}} Write"
    }
   ]
  },
  { "title": "Memory Heap / Non - Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{name=~\"^$Pod$\",area=\"heap\"} ",
     "legendFormat": "{{ name }} "
    },
    {
     "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"^$executor$\",area=\"heap\"}",
     "legendFormat": " {{ kubernetes_pod_name }} "
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{name=~\"$Pod\",area=\"nonheap\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"$executor\",area=\"nonheap\"}",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "JVM Threads & Memory Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Memory Pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name,pool)",
     "legendFormat": "{{ kubernetes_pod_name }} {{pool}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{name=~\"$Pod\"}) by (name,pool)",
     "legendFormat": "{{ name }} {{pool}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {
     "expr": "sum(jvm_threads_current{name=~\"$Pod\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Executor : Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "spark_executor_executor_threadpool_completetasks{kubernetes_pod_name=~\"$executor\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Executor : Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "spark_executor_executor_threadpool_activetasks{kubernetes_pod_name=~\"$executor\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {}
   ]
  },
  { "title": "Miscellaneous Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Executors Spawned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_name=~\"$Pod\"})",
     "legendFormat": "Executor Counts "
    }
   ]
  },
  {
   "title": "Packets Dropped : Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total{pod=~\"$Pod|$executor\"}",
     "legendFormat": "{{pod_name}} - Receive"
    },
    {
     "expr": "container_network_transmit_packets_dropped_total{pod=~\"$Pod|$executor\"}",
     "legendFormat": "{{pod_name}} - Transmit"
    }
   ]
  },
  {
   "title": "Kubernetes Pod Slice",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 88 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{pod_name=~\"$executor\"}"
    },
    {
     "expr": "container_network_receive_bytes_total{pod_name=~\"$Pod\"}"
    },
    {}
   ]
  }
 ]
}