# Default values for spark-history-server.
replicaCount: 1

nameOverride: "spark-history-server"
fullnameOverride: "spark-history-server"

deployment:
  enabled: true
  name: "deploy-spark-history-server"
  image: "arthurkretzer/spark-history-server:latest"
  pullPolicy: Always
  

pvc:
  enabled: true
  name: "pvc-spark-history-server"
  storageClassName: "longhorn"

service:
  enabled: true
  name: "svn-spark-history-server"
  type: NodePort
  nodePort: 31040

ingress:
  enabled: false
  name: "ingress-spark-history-server"
  host: "spark-history.k8s-prod1.local.parcit"


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2
    memory: 10Gi
  requests:
    cpu: 100m
    memory: 1Gi

